name: Setup and Run Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4320  # Timeout after 72 hours (4320 minutes)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Update apt-get and install main dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libcairo2 libgtk-3-0 libx11-6 libxcomposite1 libxcursor1 \
          libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
          fonts-liberation wget
          
      - name: Install libasound2t64 separately
        run: |
          sudo apt-get install -y libasound2t64
          
      - name: Install Node.js dependencies
        run: |
          npm install
          
      - name: Run the Node.js script
        run: |
          node 25-no_sandbox.js --no-sandbox
