name: Setup and Run Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # or your chosen runner (self-hosted, windows-latest, etc.)
    timeout-minutes: 2880   # Timeout after 2 days (2880 minutes)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Update apt-get and install main dependencies
        run: |
          sudo apt-get update
          
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
          
      - name: Run the Node.js script
        run: |
          python run.py
